# Generated by Django 2.1.3 on 2018-12-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181207_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reviewer',
            new_name='author',
        ),
    ]
